# This is the backend configuration for GitHub
backend:
  name: github
  repo: adzrealty/adzrealty.github.io # Your repo name
  branch: main # The branch to commit to

# This is for media files (images)
media_folder: "src/assets/images" # Where to upload images
public_folder: "/src/assets/images" # How to link to them

# This defines your content collections. You only have one: "blog"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog Post" # Used in the UI
    folder: "src/data/blog" # The path to the folder where blog posts are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template
    fields: # The fields for each document, which map to the frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "pubDatetime",
          widget: "datetime",
          format: "YYYY-MM-DDTHH:mm:ssZ",
        }
      - {
          label: "Modified Date",
          name: "modDatetime",
          widget: "datetime",
          format: "YYYY-MM-DDTHH:mm:ssZ",
          required: false,
        }
      - { label: "Author", name: "author", widget: "string", required: false }
      - {
          label: "Featured Post?",
          name: "featured",
          widget: "boolean",
          default: false,
        }
      - { label: "Draft?", name: "draft", widget: "boolean", default: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - {
          label: "OG Image URL",
          name: "ogImage",
          widget: "string",
          required: false,
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
